//! OT-2 v10.0.0 robot-server operations mapped onto a2a-lab logs, metrics, and tasks.

/// How an HTTP operation is advertised.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// Time-ordered event stream.
    Log,
    /// Numeric or 0/1 gauge.
    Metric,
    /// Mutation or object-valued read.
    Task,
    /// Flex-only or OT-2-unsupported; not advertised.
    Skip,
}

/// One robot-server operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    /// a2a-lab identifier.
    pub id: &'static str,
    /// HTTP method.
    pub method: &'static str,
    /// Path template (`{runId}` style).
    pub path: &'static str,
    /// a2a-lab domain.
    pub kind: Kind,
    /// Human-readable name.
    pub name: &'static str,
    /// What the operation does.
    pub description: &'static str,
    /// Metric unit, empty otherwise.
    pub unit: &'static str,
}

/// Composite tasks implemented in the provider, not 1:1 HTTP.
pub const COMPOSITE_TASK_IDS: &[&str] = &[
    "run_serial_dilution",
    "pause_run",
    "resume_run",
    "stop_run",
    "delete_run",
    "resume_from_recovery",
    "resume_from_recovery_assuming_false_positive",
    "execute_command",
];

/// Path+method pairs from `GET /openapi.json` on the v10.0.0 OT-2 simulator, excluding deprecated routes.
pub const OPENAPI_OPERATIONS: &[(&str, &str)] = &[
    ("GET", "/accessControl/settings"),
    ("PATCH", "/accessControl/settings"),
    ("DELETE", "/accessControl/settings"),
    ("GET", "/calibration/pipette_offset"),
    ("DELETE", "/calibration/pipette_offset"),
    ("GET", "/calibration/status"),
    ("GET", "/calibration/tip_length"),
    ("DELETE", "/calibration/tip_length"),
    ("POST", "/camera"),
    ("GET", "/camera"),
    ("POST", "/camera/cameraSettings"),
    ("GET", "/camera/cameraSettings/{cameraId}"),
    ("POST", "/camera/capturePreviewImage"),
    ("POST", "/camera/picture"),
    ("GET", "/camera/stream"),
    ("POST", "/camera/stream/settings"),
    ("GET", "/camera/stream/settings"),
    ("DELETE", "/clientData"),
    ("PUT", "/clientData/{key}"),
    ("GET", "/clientData/{key}"),
    ("DELETE", "/clientData/{key}"),
    ("POST", "/commands"),
    ("GET", "/commands"),
    ("GET", "/commands/{commandId}"),
    ("POST", "/dataFiles"),
    ("GET", "/dataFiles"),
    ("GET", "/dataFiles/{dataFileId}"),
    ("DELETE", "/dataFiles/{dataFileId}"),
    ("GET", "/dataFiles/{dataFileId}/download"),
    ("GET", "/dataFiles/{runId}/all"),
    ("GET", "/dataFiles/{runId}/images"),
    ("DELETE", "/dataFiles/{runId}/images"),
    ("GET", "/dataFiles/{runId}/images/download"),
    ("PUT", "/deck_configuration"),
    ("GET", "/deck_configuration"),
    ("GET", "/errorRecovery/settings"),
    ("PATCH", "/errorRecovery/settings"),
    ("DELETE", "/errorRecovery/settings"),
    ("GET", "/health"),
    ("POST", "/identify"),
    ("GET", "/instruments"),
    ("POST", "/labwareOffsets"),
    ("GET", "/labwareOffsets"),
    ("DELETE", "/labwareOffsets"),
    ("POST", "/labwareOffsets/searches"),
    ("DELETE", "/labwareOffsets/{id}"),
    ("GET", "/logs/{log_identifier}"),
    ("POST", "/maintenance_runs"),
    ("GET", "/maintenance_runs/current_run"),
    ("GET", "/maintenance_runs/{runId}"),
    ("DELETE", "/maintenance_runs/{runId}"),
    ("POST", "/maintenance_runs/{runId}/commands"),
    ("GET", "/maintenance_runs/{runId}/commands"),
    ("GET", "/maintenance_runs/{runId}/commands/{commandId}"),
    ("POST", "/maintenance_runs/{runId}/labware_definitions"),
    ("POST", "/maintenance_runs/{runId}/labware_offsets"),
    ("GET", "/modules"),
    ("POST", "/modules/{serial}/update"),
    ("POST", "/motors/disengage"),
    ("GET", "/motors/engaged"),
    ("GET", "/networking/status"),
    ("GET", "/pipettes"),
    ("POST", "/protocols"),
    ("GET", "/protocols"),
    ("GET", "/protocols/ids"),
    ("GET", "/protocols/{protocolId}"),
    ("DELETE", "/protocols/{protocolId}"),
    ("POST", "/protocols/{protocolId}/analyses"),
    ("GET", "/protocols/{protocolId}/analyses"),
    ("GET", "/protocols/{protocolId}/analyses/{analysisId}"),
    (
        "GET",
        "/protocols/{protocolId}/analyses/{analysisId}/asDocument",
    ),
    ("GET", "/protocols/{protocolId}/dataFiles"),
    ("PUT", "/robot/control/acknowledgeEstopDisengage"),
    ("GET", "/robot/control/estopStatus"),
    ("GET", "/robot/door/status"),
    ("POST", "/robot/home"),
    ("GET", "/robot/lights"),
    ("POST", "/robot/lights"),
    ("POST", "/runs"),
    ("GET", "/runs"),
    ("GET", "/runs/{runId}"),
    ("DELETE", "/runs/{runId}"),
    ("PATCH", "/runs/{runId}"),
    ("POST", "/runs/{runId}/actions"),
    ("POST", "/runs/{runId}/camera/cameraSettings"),
    ("POST", "/runs/{runId}/camera/capturePreviewImage"),
    ("POST", "/runs/{runId}/camera/settings"),
    ("GET", "/runs/{runId}/cameraSettings/{cameraId}"),
    ("GET", "/runs/{runId}/commandAnnotations"),
    (
        "GET",
        "/runs/{runId}/commandAnnotations/{commandAnnotationId}",
    ),
    ("GET", "/runs/{runId}/commandErrors"),
    ("POST", "/runs/{runId}/commands"),
    ("GET", "/runs/{runId}/commands"),
    ("GET", "/runs/{runId}/commands/{commandId}"),
    ("GET", "/runs/{runId}/commandsAsPreSerializedList"),
    ("GET", "/runs/{runId}/currentState"),
    ("GET", "/runs/{runId}/download"),
    ("PUT", "/runs/{runId}/errorRecoveryPolicy"),
    ("GET", "/runs/{runId}/errorRecoveryPolicy"),
    ("POST", "/runs/{runId}/labware_definitions"),
    ("POST", "/runs/{runId}/labware_offsets"),
    ("GET", "/runs/{runId}/loaded_labware_definitions"),
    ("POST", "/settings"),
    ("GET", "/settings"),
    ("POST", "/settings/log_level/local"),
    ("GET", "/settings/pipettes"),
    ("GET", "/settings/pipettes/{pipette_id}"),
    ("PATCH", "/settings/pipettes/{pipette_id}"),
    ("POST", "/settings/reset"),
    ("GET", "/settings/reset/options"),
    ("GET", "/settings/robot"),
    ("GET", "/subsystems/status"),
    ("GET", "/subsystems/status/{subsystem}"),
    ("GET", "/subsystems/updates/all"),
    ("GET", "/subsystems/updates/all/{id}"),
    ("GET", "/subsystems/updates/current"),
    ("GET", "/subsystems/updates/current/{subsystem}"),
    ("POST", "/subsystems/updates/{subsystem}"),
    ("GET", "/system/time"),
    ("PUT", "/system/time"),
    ("POST", "/wifi/configure"),
    ("POST", "/wifi/disconnect"),
    ("GET", "/wifi/eap-options"),
    ("GET", "/wifi/keys"),
    ("POST", "/wifi/keys"),
    ("DELETE", "/wifi/keys/{key_uuid}"),
    ("GET", "/wifi/list"),
];

/// Classified robot-server operations for the OT-2 v10.0.0 simulator.
pub const ENTRIES: &[Entry] = &[
    log(
        "api.log",
        "GET",
        "/logs/api.log",
        "API log",
        "GET /logs/api.log (opentrons-api journal).",
    ),
    log(
        "serial.log",
        "GET",
        "/logs/serial.log",
        "Serial log",
        "GET /logs/serial.log (Smoothie serial).",
    ),
    log(
        "server.log",
        "GET",
        "/logs/server.log",
        "Server log",
        "GET /logs/server.log (uvicorn journal).",
    ),
    log(
        "update_server.log",
        "GET",
        "/logs/update_server.log",
        "Update server log",
        "GET /logs/update_server.log.",
    ),
    log(
        "combined_api_server.log",
        "GET",
        "/logs/combined_api_server.log",
        "Combined API server log",
        "GET /logs/combined_api_server.log.",
    ),
    log(
        "can_bus.log",
        "GET",
        "/logs/can_bus.log",
        "CAN bus log",
        "GET /logs/can_bus.log (empty on OT-2).",
    ),
    log(
        "kernel.log",
        "GET",
        "/logs/kernel.log",
        "Kernel log",
        "GET /logs/kernel.log (often empty on the simulator).",
    ),
    log(
        "auth_server.log",
        "GET",
        "/logs/auth_server.log",
        "Auth server log",
        "GET /logs/auth_server.log.",
    ),
    log(
        "audit_server.log",
        "GET",
        "/logs/audit_server.log",
        "Audit server log",
        "GET /logs/audit_server.log.",
    ),
    log(
        "remote_access.log",
        "GET",
        "/logs/remote_access.log",
        "Remote access log",
        "GET /logs/remote_access.log.",
    ),
    log(
        "touchscreen.log",
        "GET",
        "/logs/touchscreen.log",
        "Touchscreen log",
        "GET /logs/touchscreen.log (Flex ODD; empty on OT-2).",
    ),
    log(
        "run_commands",
        "GET",
        "/runs/{runId}/commands",
        "Run commands",
        "Protocol Engine commands from GET /runs/{id}/commands.",
    ),
    log(
        "run_command_errors",
        "GET",
        "/runs/{runId}/commandErrors",
        "Run command errors",
        "Command errors from GET /runs/{id}/commandErrors.",
    ),
    log(
        "protocol_analyses",
        "GET",
        "/protocols/{protocolId}/analyses",
        "Protocol analyses",
        "Analysis records from uploaded protocols.",
    ),
    log(
        "stateless_commands",
        "GET",
        "/commands",
        "Stateless commands",
        "Commands issued through POST /commands since boot.",
    ),
    metric(
        "healthy",
        "GET",
        "/health",
        "Healthy",
        "1 when robot-server /health succeeds.",
        "count",
    ),
    metric(
        "disk_available_mb",
        "GET",
        "/health",
        "Disk available",
        "systemAvailableMb from GET /health disk_details.",
        "megabyte",
    ),
    metric(
        "run_progress_percent",
        "GET",
        "/runs/{runId}/commands",
        "Run progress",
        "Percent of current-run commands that have completed.",
        "percent",
    ),
    metric(
        "run_command_count",
        "GET",
        "/runs/{runId}/commands",
        "Run command count",
        "Number of commands on the current run.",
        "count",
    ),
    metric(
        "door_open",
        "GET",
        "/robot/door/status",
        "Door open",
        "1 when GET /robot/door/status reports open.",
        "count",
    ),
    metric(
        "lights_on",
        "GET",
        "/robot/lights",
        "Lights on",
        "1 when rail lights are on.",
        "count",
    ),
    metric(
        "pipette_count",
        "GET",
        "/pipettes",
        "Pipette count",
        "Attached pipettes from GET /pipettes.",
        "count",
    ),
    metric(
        "instrument_count",
        "GET",
        "/instruments",
        "Instrument count",
        "Attached instruments from GET /instruments.",
        "count",
    ),
    metric(
        "module_count",
        "GET",
        "/modules",
        "Module count",
        "Attached modules from GET /modules.",
        "count",
    ),
    task(
        "get_access_control_settings",
        "GET",
        "/accessControl/settings",
        "Access control settings",
        "GET /accessControl/settings.",
    ),
    task(
        "patch_access_control_settings",
        "PATCH",
        "/accessControl/settings",
        "Set access control settings",
        "PATCH /accessControl/settings.",
    ),
    task(
        "delete_access_control_settings",
        "DELETE",
        "/accessControl/settings",
        "Reset access control settings",
        "DELETE /accessControl/settings.",
    ),
    task(
        "get_pipette_offset_calibrations",
        "GET",
        "/calibration/pipette_offset",
        "Pipette offset calibrations",
        "List pipette offset calibrations.",
    ),
    task(
        "delete_pipette_offset_calibration",
        "DELETE",
        "/calibration/pipette_offset",
        "Delete pipette offset calibration",
        "Delete pipette offset calibration.",
    ),
    task(
        "get_calibration_status",
        "GET",
        "/calibration/status",
        "Calibration status",
        "GET /calibration/status.",
    ),
    task(
        "get_tip_length_calibrations",
        "GET",
        "/calibration/tip_length",
        "Tip length calibrations",
        "List tip length calibrations.",
    ),
    task(
        "delete_tip_length_calibration",
        "DELETE",
        "/calibration/tip_length",
        "Delete tip length calibration",
        "Delete tip length calibration.",
    ),
    task(
        "post_camera",
        "POST",
        "/camera",
        "Set camera",
        "POST /camera.",
    ),
    task("get_camera", "GET", "/camera", "Get camera", "GET /camera."),
    task(
        "post_camera_settings",
        "POST",
        "/camera/cameraSettings",
        "Set camera capture settings",
        "POST /camera/cameraSettings.",
    ),
    task(
        "get_camera_settings",
        "GET",
        "/camera/cameraSettings/{cameraId}",
        "Get camera capture settings",
        "GET /camera/cameraSettings/{id}.",
    ),
    task(
        "post_camera_preview",
        "POST",
        "/camera/capturePreviewImage",
        "Capture preview image",
        "POST /camera/capturePreviewImage.",
    ),
    task(
        "post_camera_picture",
        "POST",
        "/camera/picture",
        "Capture picture",
        "POST /camera/picture.",
    ),
    task(
        "get_camera_stream",
        "GET",
        "/camera/stream",
        "Camera stream",
        "GET /camera/stream.",
    ),
    skip(
        "post_camera_stream_settings",
        "POST",
        "/camera/stream/settings",
        "Set camera stream settings",
        "Flex live stream; OT-2 returns 400.",
    ),
    skip(
        "get_camera_stream_settings",
        "GET",
        "/camera/stream/settings",
        "Camera stream settings",
        "Flex live stream; OT-2 returns 400.",
    ),
    task(
        "delete_all_client_data",
        "DELETE",
        "/clientData",
        "Delete all client data",
        "DELETE /clientData.",
    ),
    task(
        "put_client_data",
        "PUT",
        "/clientData/{key}",
        "Set client data",
        "PUT /clientData/{key}.",
    ),
    task(
        "get_client_data",
        "GET",
        "/clientData/{key}",
        "Get client data",
        "GET /clientData/{key}.",
    ),
    task(
        "delete_client_data",
        "DELETE",
        "/clientData/{key}",
        "Delete client data",
        "DELETE /clientData/{key}.",
    ),
    task(
        "post_commands",
        "POST",
        "/commands",
        "Create stateless command",
        "POST /commands.",
    ),
    task(
        "get_stateless_command",
        "GET",
        "/commands/{commandId}",
        "Get stateless command",
        "Read one POST /commands result.",
    ),
    task(
        "post_data_files",
        "POST",
        "/dataFiles",
        "Upload data file",
        "POST /dataFiles (multipart).",
    ),
    task(
        "get_data_files",
        "GET",
        "/dataFiles",
        "List data files",
        "GET /dataFiles.",
    ),
    task(
        "get_data_file",
        "GET",
        "/dataFiles/{dataFileId}",
        "Get data file",
        "GET /dataFiles/{id}.",
    ),
    task(
        "delete_data_file",
        "DELETE",
        "/dataFiles/{dataFileId}",
        "Delete data file",
        "DELETE /dataFiles/{id}.",
    ),
    task(
        "get_data_file_download",
        "GET",
        "/dataFiles/{dataFileId}/download",
        "Download data file",
        "GET /dataFiles/{id}/download.",
    ),
    task(
        "get_run_data_files",
        "GET",
        "/dataFiles/{runId}/all",
        "List run data files",
        "GET /dataFiles/{runId}/all.",
    ),
    task(
        "get_run_images",
        "GET",
        "/dataFiles/{runId}/images",
        "List run images",
        "GET /dataFiles/{runId}/images.",
    ),
    task(
        "delete_run_images",
        "DELETE",
        "/dataFiles/{runId}/images",
        "Delete run images",
        "DELETE /dataFiles/{runId}/images.",
    ),
    task(
        "get_run_images_download",
        "GET",
        "/dataFiles/{runId}/images/download",
        "Download run images",
        "GET /dataFiles/{runId}/images/download.",
    ),
    skip(
        "put_deck_configuration",
        "PUT",
        "/deck_configuration",
        "Set deck configuration",
        "Flex-only.",
    ),
    skip(
        "get_deck_configuration",
        "GET",
        "/deck_configuration",
        "Deck configuration",
        "Flex-only.",
    ),
    task(
        "get_error_recovery_settings",
        "GET",
        "/errorRecovery/settings",
        "Error recovery settings",
        "GET /errorRecovery/settings.",
    ),
    task(
        "patch_error_recovery_settings",
        "PATCH",
        "/errorRecovery/settings",
        "Patch error recovery settings",
        "PATCH /errorRecovery/settings.",
    ),
    task(
        "delete_error_recovery_settings",
        "DELETE",
        "/errorRecovery/settings",
        "Reset error recovery settings",
        "DELETE /errorRecovery/settings.",
    ),
    task(
        "post_identify",
        "POST",
        "/identify",
        "Identify robot",
        "Blink gantry lights (query seconds).",
    ),
    task(
        "get_instruments",
        "GET",
        "/instruments",
        "List instruments",
        "List attached instruments.",
    ),
    task(
        "post_labware_offsets",
        "POST",
        "/labwareOffsets",
        "Create labware offset",
        "POST /labwareOffsets.",
    ),
    task(
        "get_labware_offsets",
        "GET",
        "/labwareOffsets",
        "List labware offsets",
        "GET /labwareOffsets.",
    ),
    task(
        "delete_labware_offsets",
        "DELETE",
        "/labwareOffsets",
        "Delete labware offsets",
        "DELETE /labwareOffsets.",
    ),
    task(
        "post_labware_offset_searches",
        "POST",
        "/labwareOffsets/searches",
        "Search labware offsets",
        "POST /labwareOffsets/searches.",
    ),
    task(
        "delete_labware_offset",
        "DELETE",
        "/labwareOffsets/{id}",
        "Delete labware offset",
        "DELETE /labwareOffsets/{id}.",
    ),
    task(
        "post_maintenance_runs",
        "POST",
        "/maintenance_runs",
        "Create maintenance run",
        "Create a maintenance run.",
    ),
    task(
        "get_current_maintenance_run",
        "GET",
        "/maintenance_runs/current_run",
        "Get current maintenance run",
        "GET /maintenance_runs/current_run.",
    ),
    task(
        "get_maintenance_run",
        "GET",
        "/maintenance_runs/{runId}",
        "Get maintenance run",
        "Read one maintenance run.",
    ),
    task(
        "delete_maintenance_run",
        "DELETE",
        "/maintenance_runs/{runId}",
        "Delete maintenance run",
        "Delete a maintenance run.",
    ),
    task(
        "post_maintenance_run_commands",
        "POST",
        "/maintenance_runs/{runId}/commands",
        "Enqueue maintenance command",
        "POST /maintenance_runs/{id}/commands.",
    ),
    task(
        "get_maintenance_run_commands",
        "GET",
        "/maintenance_runs/{runId}/commands",
        "List maintenance commands",
        "GET /maintenance_runs/{id}/commands.",
    ),
    task(
        "get_maintenance_run_command",
        "GET",
        "/maintenance_runs/{runId}/commands/{commandId}",
        "Get maintenance command",
        "GET /maintenance_runs/{id}/commands/{commandId}.",
    ),
    task(
        "post_maintenance_labware_definitions",
        "POST",
        "/maintenance_runs/{runId}/labware_definitions",
        "Add maintenance labware definition",
        "POST /maintenance_runs/{id}/labware_definitions.",
    ),
    task(
        "post_maintenance_labware_offsets",
        "POST",
        "/maintenance_runs/{runId}/labware_offsets",
        "Add maintenance labware offset",
        "POST /maintenance_runs/{id}/labware_offsets.",
    ),
    task(
        "get_modules",
        "GET",
        "/modules",
        "List modules",
        "List attached modules.",
    ),
    task(
        "post_module_update",
        "POST",
        "/modules/{serial}/update",
        "Update module firmware",
        "POST /modules/{serial}/update.",
    ),
    task(
        "post_motors_disengage",
        "POST",
        "/motors/disengage",
        "Disengage motors",
        "POST /motors/disengage.",
    ),
    task(
        "get_motors_engaged",
        "GET",
        "/motors/engaged",
        "Motors engaged",
        "GET /motors/engaged.",
    ),
    task(
        "get_networking_status",
        "GET",
        "/networking/status",
        "Networking status",
        "GET /networking/status.",
    ),
    task(
        "get_pipettes",
        "GET",
        "/pipettes",
        "List pipettes",
        "GET /pipettes.",
    ),
    task(
        "post_protocols",
        "POST",
        "/protocols",
        "Upload protocol",
        "POST /protocols (multipart).",
    ),
    task(
        "get_protocols",
        "GET",
        "/protocols",
        "List protocols",
        "List uploaded protocols.",
    ),
    task(
        "get_protocol_ids",
        "GET",
        "/protocols/ids",
        "List protocol ids",
        "List protocol identifiers.",
    ),
    task(
        "get_protocol",
        "GET",
        "/protocols/{protocolId}",
        "Get protocol",
        "Read one protocol resource.",
    ),
    task(
        "delete_protocol",
        "DELETE",
        "/protocols/{protocolId}",
        "Delete protocol",
        "Delete a protocol resource.",
    ),
    task(
        "post_protocol_analyses",
        "POST",
        "/protocols/{protocolId}/analyses",
        "Start protocol analysis",
        "Request a new protocol analysis.",
    ),
    task(
        "get_protocol_analysis",
        "GET",
        "/protocols/{protocolId}/analyses/{analysisId}",
        "Get protocol analysis",
        "Read one protocol analysis.",
    ),
    task(
        "get_protocol_analysis_document",
        "GET",
        "/protocols/{protocolId}/analyses/{analysisId}/asDocument",
        "Get analysis document",
        "Raw analysis document.",
    ),
    task(
        "get_protocol_data_files",
        "GET",
        "/protocols/{protocolId}/dataFiles",
        "List protocol data files",
        "Data files referenced by a protocol.",
    ),
    skip(
        "put_acknowledge_estop",
        "PUT",
        "/robot/control/acknowledgeEstopDisengage",
        "Acknowledge estop",
        "Flex-only.",
    ),
    skip(
        "get_estop_status",
        "GET",
        "/robot/control/estopStatus",
        "Estop status",
        "Flex-only.",
    ),
    task(
        "get_door_status",
        "GET",
        "/robot/door/status",
        "Get door status",
        "Read robot door open/closed.",
    ),
    task(
        "post_robot_home",
        "POST",
        "/robot/home",
        "Home robot",
        "POST /robot/home.",
    ),
    task(
        "get_robot_lights",
        "GET",
        "/robot/lights",
        "Get lights",
        "Read rail light state.",
    ),
    task(
        "post_robot_lights",
        "POST",
        "/robot/lights",
        "Set lights",
        "Turn rail lights on or off.",
    ),
    task(
        "post_runs",
        "POST",
        "/runs",
        "Create run",
        "Create a protocol run.",
    ),
    task(
        "get_runs",
        "GET",
        "/runs",
        "List runs",
        "List protocol runs.",
    ),
    task(
        "get_run",
        "GET",
        "/runs/{runId}",
        "Get run",
        "Read one run.",
    ),
    task(
        "http_delete_run",
        "DELETE",
        "/runs/{runId}",
        "HTTP delete run",
        "DELETE /runs/{id} as a primitive HTTP task.",
    ),
    task(
        "patch_run",
        "PATCH",
        "/runs/{runId}",
        "Patch run",
        "Update a run (for example current=false).",
    ),
    task(
        "post_run_actions",
        "POST",
        "/runs/{runId}/actions",
        "Create run action",
        "POST /runs/{id}/actions.",
    ),
    task(
        "post_run_camera_capture_settings",
        "POST",
        "/runs/{runId}/camera/cameraSettings",
        "Set run camera capture settings",
        "POST /runs/{id}/camera/cameraSettings.",
    ),
    task(
        "post_run_camera_preview",
        "POST",
        "/runs/{runId}/camera/capturePreviewImage",
        "Capture run camera preview",
        "POST /runs/{id}/camera/capturePreviewImage.",
    ),
    task(
        "post_run_camera_settings",
        "POST",
        "/runs/{runId}/camera/settings",
        "Set run camera settings",
        "POST /runs/{id}/camera/settings.",
    ),
    task(
        "get_run_camera_settings",
        "GET",
        "/runs/{runId}/cameraSettings/{cameraId}",
        "Get run camera settings",
        "GET /runs/{id}/cameraSettings/{cameraId}.",
    ),
    task(
        "get_run_command_annotations",
        "GET",
        "/runs/{runId}/commandAnnotations",
        "Get command annotations",
        "Command annotations on a run.",
    ),
    task(
        "get_run_command_annotation",
        "GET",
        "/runs/{runId}/commandAnnotations/{commandAnnotationId}",
        "Get command annotation",
        "One command annotation.",
    ),
    task(
        "post_run_commands",
        "POST",
        "/runs/{runId}/commands",
        "Enqueue run command",
        "POST /runs/{id}/commands.",
    ),
    task(
        "get_run_command",
        "GET",
        "/runs/{runId}/commands/{commandId}",
        "Get run command",
        "Read one Protocol Engine command.",
    ),
    task(
        "get_run_commands_as_list",
        "GET",
        "/runs/{runId}/commandsAsPreSerializedList",
        "Get pre-serialized commands",
        "Completed-run command dump.",
    ),
    task(
        "get_run_current_state",
        "GET",
        "/runs/{runId}/currentState",
        "Get run current state",
        "GET /runs/{id}/currentState.",
    ),
    task(
        "get_run_download",
        "GET",
        "/runs/{runId}/download",
        "Download run files",
        "GET /runs/{id}/download.",
    ),
    task(
        "put_run_error_recovery_policy",
        "PUT",
        "/runs/{runId}/errorRecoveryPolicy",
        "Set error recovery policy",
        "Replace a run's error recovery policy.",
    ),
    task(
        "get_run_error_recovery_policy",
        "GET",
        "/runs/{runId}/errorRecoveryPolicy",
        "Get error recovery policy",
        "Read a run's error recovery policy.",
    ),
    task(
        "post_run_labware_definitions",
        "POST",
        "/runs/{runId}/labware_definitions",
        "Add run labware definition",
        "POST /runs/{id}/labware_definitions.",
    ),
    task(
        "post_run_labware_offsets",
        "POST",
        "/runs/{runId}/labware_offsets",
        "Add run labware offsets",
        "POST /runs/{id}/labware_offsets.",
    ),
    task(
        "get_run_loaded_labware_definitions",
        "GET",
        "/runs/{runId}/loaded_labware_definitions",
        "Get loaded labware definitions",
        "Labware definitions used by a run.",
    ),
    task(
        "post_settings",
        "POST",
        "/settings",
        "Set setting",
        "POST /settings.",
    ),
    task(
        "get_settings",
        "GET",
        "/settings",
        "Get settings",
        "GET /settings.",
    ),
    task(
        "post_settings_log_level_local",
        "POST",
        "/settings/log_level/local",
        "Set local log level",
        "POST /settings/log_level/local.",
    ),
    task(
        "get_settings_pipettes",
        "GET",
        "/settings/pipettes",
        "Pipette settings",
        "GET /settings/pipettes.",
    ),
    task(
        "get_settings_pipette",
        "GET",
        "/settings/pipettes/{pipette_id}",
        "Get pipette settings",
        "GET /settings/pipettes/{id}.",
    ),
    task(
        "patch_settings_pipette",
        "PATCH",
        "/settings/pipettes/{pipette_id}",
        "Patch pipette settings",
        "PATCH /settings/pipettes/{id}.",
    ),
    task(
        "post_settings_reset",
        "POST",
        "/settings/reset",
        "Reset settings",
        "POST /settings/reset.",
    ),
    task(
        "get_settings_reset_options",
        "GET",
        "/settings/reset/options",
        "Reset options",
        "GET /settings/reset/options.",
    ),
    task(
        "get_settings_robot",
        "GET",
        "/settings/robot",
        "Robot settings",
        "GET /settings/robot.",
    ),
    skip(
        "get_subsystems",
        "GET",
        "/subsystems/status",
        "Subsystem status",
        "Flex-only.",
    ),
    skip(
        "get_subsystem",
        "GET",
        "/subsystems/status/{subsystem}",
        "Get subsystem",
        "Flex-only.",
    ),
    skip(
        "get_subsystem_updates",
        "GET",
        "/subsystems/updates/all",
        "List subsystem updates",
        "Flex-only.",
    ),
    skip(
        "get_subsystem_update",
        "GET",
        "/subsystems/updates/all/{id}",
        "Get subsystem update",
        "Flex-only.",
    ),
    skip(
        "get_current_subsystem_updates",
        "GET",
        "/subsystems/updates/current",
        "Current subsystem updates",
        "Flex-only.",
    ),
    skip(
        "get_current_subsystem_update",
        "GET",
        "/subsystems/updates/current/{subsystem}",
        "Current subsystem update",
        "Flex-only.",
    ),
    skip(
        "post_subsystem_update",
        "POST",
        "/subsystems/updates/{subsystem}",
        "Update subsystem",
        "Flex-only.",
    ),
    task(
        "get_system_time",
        "GET",
        "/system/time",
        "Get system time",
        "GET /system/time.",
    ),
    task(
        "put_system_time",
        "PUT",
        "/system/time",
        "Set system time",
        "PUT /system/time.",
    ),
    task(
        "post_wifi_configure",
        "POST",
        "/wifi/configure",
        "Configure Wi-Fi",
        "POST /wifi/configure.",
    ),
    task(
        "post_wifi_disconnect",
        "POST",
        "/wifi/disconnect",
        "Disconnect Wi-Fi",
        "POST /wifi/disconnect.",
    ),
    task(
        "get_wifi_eap_options",
        "GET",
        "/wifi/eap-options",
        "Wi-Fi EAP options",
        "GET /wifi/eap-options.",
    ),
    task(
        "get_wifi_keys",
        "GET",
        "/wifi/keys",
        "List Wi-Fi keys",
        "GET /wifi/keys.",
    ),
    task(
        "post_wifi_keys",
        "POST",
        "/wifi/keys",
        "Add Wi-Fi key",
        "POST /wifi/keys.",
    ),
    task(
        "delete_wifi_key",
        "DELETE",
        "/wifi/keys/{key_uuid}",
        "Delete Wi-Fi key",
        "DELETE /wifi/keys/{id}.",
    ),
    task(
        "get_wifi_list",
        "GET",
        "/wifi/list",
        "List Wi-Fi",
        "Scan visible Wi-Fi networks.",
    ),
];

const fn log(
    id: &'static str,
    method: &'static str,
    path: &'static str,
    name: &'static str,
    description: &'static str,
) -> Entry {
    Entry {
        id,
        method,
        path,
        kind: Kind::Log,
        name,
        description,
        unit: "",
    }
}

const fn metric(
    id: &'static str,
    method: &'static str,
    path: &'static str,
    name: &'static str,
    description: &'static str,
    unit: &'static str,
) -> Entry {
    Entry {
        id,
        method,
        path,
        kind: Kind::Metric,
        name,
        description,
        unit,
    }
}

const fn task(
    id: &'static str,
    method: &'static str,
    path: &'static str,
    name: &'static str,
    description: &'static str,
) -> Entry {
    Entry {
        id,
        method,
        path,
        kind: Kind::Task,
        name,
        description,
        unit: "",
    }
}

const fn skip(
    id: &'static str,
    method: &'static str,
    path: &'static str,
    name: &'static str,
    description: &'static str,
) -> Entry {
    Entry {
        id,
        method,
        path,
        kind: Kind::Skip,
        name,
        description,
        unit: "",
    }
}

/// Returns inventory rows of `kind`.
pub fn of_kind(kind: Kind) -> impl Iterator<Item = &'static Entry> {
    ENTRIES.iter().filter(move |entry| entry.kind == kind)
}

/// Looks up a non-skip task by id.
#[must_use]
pub fn task_entry(id: &str) -> Option<&'static Entry> {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == Kind::Task && entry.id == id)
}

/// True when the row is a GET-backed task.
#[must_use]
pub fn is_read(entry: &Entry) -> bool {
    entry.kind == Kind::Task && entry.method == "GET"
}

/// True when this robot-server path is inventoried (including Flex skips).
#[must_use]
pub fn covers(method: &str, path: &str) -> bool {
    if method == "GET" && path == "/logs/{log_identifier}" {
        return of_kind(Kind::Log).any(|entry| entry.path.starts_with("/logs/"));
    }
    ENTRIES
        .iter()
        .any(|entry| entry.method == method && entry.path == path)
}
